uint32 routine
uint32 head_curr
uint32 device
uint32 device_number
string carrier 
float64[] offsets [0.0, 0.0] # Only for Place Routine -> Format: [X Offset, Y Offset]
---
bool success
string message
float64[] offsets # Only for Align Device Routine -> Format: [X Offset, Y Offset]